spring:
  application:
    name: pets

#  jpa:
#    database: postgresql
  datasource:
    url: ${POSTGRES_URL:jdbc:postgresql://127.0.0.1:5433/adotai}
    username: ${POSTGRES_USERNAME:docker}
    password: ${POSTGRES_PASSWORD:docker}
